export { default as CategoriesRoute } from './categoriesRoutes';
export { default as MusicsRoute } from './musicsRoutes';
export { default as MoviesRoute } from './moviesRoutes';
export { default as UsersRoute } from './usersRoutes';
export { default as GamesRoute } from './gamesRoutes';
export { default as HistoryRoute } from './historyRoutes';
export { default as TodayRoute } from './todayRoutes';
export { default as HistoryTodayRoute } from './historyTodayRoutes';
export { default as TVShowsRoute } from './tvShowsRoutes';
